### ISSUE TITLE
BaseUnitBanner NoSuchMethodException

### ISSUE THREAD

**Issue by edinofricaniago** [karizal/ads-base#1]
```
Caused by: java.lang.NoSuchMethodException: com.karizal.ads_base.unit.BaseUnitBanner.<init> []
	at java.lang.Class.getConstructor0(Class.java:3325)
	at java.lang.Class.getConstructor(Class.java:2485)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.kt:84) 
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:358) 
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
```

**Comment by edinofricaniago** [comment]
Step to reproduce.

1. Open App with Banner Ads
2. Slide Down Quick Menu from Android and Change Dark to Light Mode or vice versa.
3. App will crash and throw that exceptions.
